name: Python CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repo
      uses: actions/checkout@v5

        
    - name: setup our python
      uses: actions/setup-python@v5
      with :
         python-version: '3.10'
            - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip3 install pytest

    - name: Run tests
      run: |
        pytest -v



